Repository LBL-EESA/TECA, pull requests merged in 2019-05, with the labels that each got.

#214 Fixes for pythonpath and rpath distutils install issues
  alg/CMakeLists.txt
  python/CMakeLists.txt
  setup.py
Labels: bug

#225 add an MPI error handler callback and use it in regression tests
  CMake/teca_test.cmake
  io/teca_table_writer.cxx
  io/teca_table_writer.h
  system/teca_system_interface.cxx
  system/teca_system_interface.h
  test/CMakeLists.txt
  test/python/test_bayesian_ar_detect.py
  test/python/test_database.py
  test/python/test_programmable_map_reduce.py
  test/python/test_tc_candidates.py
  test/python/test_tc_trajectory_scalars.py
  test/test_ar_detect.cpp
  test/test_bayesian_ar_detect.cpp
  test/test_binary_stream.cpp
  test/test_cartesian_mesh_regrid.cpp
  test/test_cf_reader.cpp
  test/test_dataset_diff.cpp
  test/test_descriptive_statistics.cpp
  test/test_mpi_error_handler.cpp
  test/test_pipeline_index_reduce.cpp
  test/test_table_reader.cpp
  test/test_table_reader_distribute.cpp
  test/test_table_writer.cpp
  test/test_tc_candidates.cpp
  test/test_tc_wind_radii.cpp
Labels: feature

#231 more executive generalization
  alg/teca_bayesian_ar_detect.cxx
  alg/teca_dataset_diff.cxx
  alg/teca_dataset_diff.h
  alg/teca_dataset_source.cxx
  alg/teca_dataset_source.h
  alg/teca_programmable_algorithm.h
  alg/teca_tc_trajectory_scalars.py
  apps/teca_convert_table.py
  core/teca_algorithm_executive.cxx
  core/teca_algorithm_executive.h
  core/teca_common.h
  core/teca_index_executive.cxx
  core/teca_index_reduce.cxx
  core/teca_parallel_id.cxx
  data/teca_coordinate_util.h
  io/teca_cf_reader.cxx
  io/teca_table_reader.cxx
  io/teca_table_writer.cxx
  io/teca_vtk_cartesian_mesh_writer.cxx
  python/teca_py.i
  python/teca_py_core.i
  python/teca_py_object.h
  test/python/CMakeLists.txt
  test/python/test_binary_stream.py
  test/python/test_database.py
  test/python/test_nested_pipeline.py
  test/teca_test_util.cxx
  test/teca_test_util.h
  test/test_ar_detect.cpp
  test/test_bayesian_ar_detect.cpp
  test/test_binary_segmentation.cpp
  test/test_binary_stream.cpp
  test/test_component_area_filter.cpp
  test/test_connected_components.cpp
  test/test_dataset_diff.cpp
  test/test_descriptive_statistics.cpp
  test/test_evaluate_expression_table.cpp
  test/test_event_filter.cpp
  test/test_table_reader.cpp
  test/test_table_reader_distribute.cpp
  test/test_table_region_mask.cpp
  test/test_table_remove_rows.cpp
  test/test_table_sort.cpp
  test/test_table_writer.cpp
  test/test_tc_candidates.cpp
  test/test_tc_classify.cpp
  test/test_tc_trajectory.cpp
  test/test_tc_wind_radii.cpp
Labels: bug, feature

#209 Closes #185 Supporting multiple files for CF reader
  apps/teca_metadata_probe.cpp
  apps/teca_tc_detect.cpp
  io/teca_cf_reader.cxx
  io/teca_cf_reader.h
  test/CMakeLists.txt
  test/test_ar_detect.cpp
  test/test_descriptive_statistics.cpp
Labels: feature

#238 Coordinate system normalization
  alg/CMakeLists.txt
  alg/teca_2d_component_area.cxx
  alg/teca_ar_detect.cxx
  alg/teca_cartesian_mesh_regrid.cxx
  alg/teca_cartesian_mesh_regrid.h
  alg/teca_cartesian_mesh_source.cxx
  alg/teca_cartesian_mesh_source.h
  alg/teca_dataset_diff.cxx
  alg/teca_dataset_diff.h
  alg/teca_normalize_coordinates.cxx
  alg/teca_normalize_coordinates.h
  apps/teca_ar_detect.cpp
  apps/teca_dataset_metadata.py
  apps/teca_tc_detect.cpp
  apps/teca_tc_storm_size.cpp
  apps/teca_tc_trajectory.cpp
  apps/teca_tc_wind_radii.cpp
  data/teca_coordinate_util.h
  doc/source/python_for_devel.py
  io/CMakeLists.txt
  io/teca_cartesian_mesh_reader.cxx
  io/teca_cartesian_mesh_reader.h
  io/teca_cartesian_mesh_writer.cxx
  io/teca_cartesian_mesh_writer.h
  python/teca_py_alg.i
  python/teca_py_io.i
  test/CMakeLists.txt
  test/python/test_bayesian_ar_detect.py
  test/python/test_cf_reader.py
  test/python/test_component_area_filter.py
  test/python/test_connected_components.py
  test/python/test_derived_quantity.py
  test/python/test_latitude_damper.py
  test/python/test_programmable_algorithm.py
  test/python/test_programmable_map_reduce.py
  test/python/test_tc_candidates.py
  test/python/test_vector_ops.py
  test/test_2d_component_area.cpp
  test/test_ar_detect.cpp
  test/test_bayesian_ar_detect.cpp
  test/test_binary_segmentation.cpp
  test/test_cartesian_mesh_regrid.cpp
  test/test_cf_reader.cpp
  test/test_component_area_filter.cpp
  test/test_connected_components.cpp
  test/test_descriptive_statistics.cpp
  test/test_latitude_damper.cpp
  test/test_normalize_coordinates.cpp
  test/test_tc_candidates.cpp
  test/test_tc_wind_radii.cpp
  test/test_temporal_average.cpp
Labels: bug, feature
